#!/usr/bin/env python
#
# @file    fileHeaders.py
# @brief   creates the headers for files
# @author  Frank Bergmann
# @author  Sarah Keating
#
# <!--------------------------------------------------------------------------
#
# Copyright (c) 2013-2014 by the California Institute of Technology
# (California, USA), the European Bioinformatics Institute (EMBL-EBI, UK)
# and the University of Heidelberg (Germany), with support from the National
# Institutes of Health (USA) under grant R01GM070923.  All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# Neither the name of the California Institute of Technology (Caltech), nor
# of the European Bioinformatics Institute (EMBL-EBI), nor of the University
# of Heidelberg, nor the names of any contributors, may be used to endorse
# or promote products derived from this software without specific prior
# written permission.
# ------------------------------------------------------------------------ -->

import sys
import strFunctions

def addFilename(outFile, filename, element):
  outFile.write('/**\n')
  outFile.write(' * @file:   {0}\n'.format(filename))
  outFile.write(' * @brief:  Implementation of the {0} class\n'.format(element))
  outFile.write(' * @author: SBMLTeam\n *\n')
  
def addLicence(outFile):
  outFile.write(' * <!--------------------------------------------------------------------------\n')
  outFile.write(' * This file is part of libSBML.  Please visit http://sbml.org for more\n')
  outFile.write(' * information about SBML, and the latest version of libSBML.\n')
  outFile.write(' *\n')
  outFile.write(' * Copyright (C) 2013-2014 jointly by the following organizations:\n')
  outFile.write(' *     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write(' *     2. EMBL European Bioinformatics Institute (EMBL-EBI), Hinxton, UK\n')
  outFile.write(' *     3. University of Heidelberg, Heidelberg, Germany\n')
  outFile.write(' *\n')
  outFile.write(' * Copyright (C) 2009-2013 jointly by the following organizations:\n')
  outFile.write(' *     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write(' *     2. EMBL European Bioinformatics Institute (EMBL-EBI), Hinxton, UK\n')
  outFile.write(' *\n')
  outFile.write(' * Copyright (C) 2006-2008 by the California Institute of Technology,\n')
  outFile.write(' *     Pasadena, CA, USA \n')
  outFile.write(' *\n')  
  outFile.write(' * Copyright (C) 2002-2005 jointly by the following organizations:\n') 
  outFile.write(' *     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write(' *     2. Japan Science and Technology Agency, Japan\n')
  outFile.write(' *\n')
  outFile.write(' * This library is free software; you can redistribute it and/or modify it\n')
  outFile.write(' * under the terms of the GNU Lesser General Public License as published by\n')
  outFile.write(' * the Free Software Foundation.  A copy of the license agreement is provided\n')
  outFile.write(' * in the file named "LICENSE.txt" included with this software distribution\n')
  outFile.write(' * and also available online as http://sbml.org/software/libsbml/license.html\n')
  outFile.write(' * ------------------------------------------------------------------------ -->\n')
  outFile.write(' */\n')
    
def addCMakeFilename(outFile, filename, element):
  outFile.write('#################################################################################\n')
  outFile.write('#\n')
  outFile.write('# @file:   {0}\n'.format(filename))
  outFile.write('# @brief:  CMake configuration for L3 {0} package\n'.format(strFunctions.cap(element)))
  outFile.write('# @author: Generated by autocreate code\n#\n')

def addCMakeLicence(outFile):
  outFile.write('# <!--------------------------------------------------------------------------\n')
  outFile.write('# This file is part of libSBML.  Please visit http://sbml.org for more\n')
  outFile.write('# information about SBML, and the latest version of libSBML.\n')
  outFile.write('#\n')
  outFile.write('# Copyright (C) 2013-2014 jointly by the following organizations:\n')
  outFile.write('#     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write('#     2. EMBL European Bioinformatics Institute (EMBL-EBI), Hinxton, UK\n')
  outFile.write('#     3. University of Heidelberg, Heidelberg, Germany\n')
  outFile.write('#\n')
  outFile.write('# Copyright (C) 2009-2013 jointly by the following organizations:\n')
  outFile.write('#     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write('#     2. EMBL European Bioinformatics Institute (EMBL-EBI), Hinxton, UK\n')
  outFile.write('#\n')
  outFile.write('# Copyright (C) 2006-2008 by the California Institute of Technology,\n')
  outFile.write('#     Pasadena, CA, USA \n')
  outFile.write('#\n')  
  outFile.write('# Copyright (C) 2002-2005 jointly by the following organizations:\n') 
  outFile.write('#     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write('#     2. Japan Science and Technology Agency, Japan\n')
  outFile.write('#\n')
  outFile.write('# This library is free software; you can redistribute it and/or modify it\n')
  outFile.write('# under the terms of the GNU Lesser General Public License as published by\n')
  outFile.write('# the Free Software Foundation.  A copy of the license agreement is provided\n')
  outFile.write('# in the file named "LICENSE.txt" included with this software distribution\n')
  outFile.write('# and also available online as http://sbml.org/software/libsbml/license.html\n')
  outFile.write('# ------------------------------------------------------------------------ -->\n')
  outFile.write('#\n')
  