#!/usr/bin/env python
#
# @file   fileHeaders.py
# @brief  Create the directory structure for package code
# @author Sarah Keating
#

import sys
import strFunctions

def addFilename(outFile, filename, element):
  outFile.write('/**\n')
  outFile.write(' * @file:   {0}\n'.format(filename))
  outFile.write(' * @brief:  Implementation of the {0} class\n'.format(element))
  outFile.write(' * @author: SBMLTeam\n *\n')
  
def addLicence(outFile):
  outFile.write(' * <!--------------------------------------------------------------------------\n')
  outFile.write(' * This file is part of libSBML.  Please visit http://sbml.org for more\n')
  outFile.write(' * information about SBML, and the latest version of libSBML.\n')
  outFile.write(' *\n')
  outFile.write(' * Copyright (C) 2013-2014 jointly by the following organizations:\n')
  outFile.write(' *     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write(' *     2. EMBL European Bioinformatics Institute (EMBL-EBI), Hinxton, UK\n')
  outFile.write(' *     3. University of Heidelberg, Heidelberg, Germany\n')
  outFile.write(' *\n')
  outFile.write(' * Copyright (C) 2009-2013 jointly by the following organizations:\n')
  outFile.write(' *     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write(' *     2. EMBL European Bioinformatics Institute (EMBL-EBI), Hinxton, UK\n')
  outFile.write(' *\n')
  outFile.write(' * Copyright (C) 2006-2008 by the California Institute of Technology,\n')
  outFile.write(' *     Pasadena, CA, USA \n')
  outFile.write(' *\n')  
  outFile.write(' * Copyright (C) 2002-2005 jointly by the following organizations:\n') 
  outFile.write(' *     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write(' *     2. Japan Science and Technology Agency, Japan\n')
  outFile.write(' *\n')
  outFile.write(' * This library is free software; you can redistribute it and/or modify it\n')
  outFile.write(' * under the terms of the GNU Lesser General Public License as published by\n')
  outFile.write(' * the Free Software Foundation.  A copy of the license agreement is provided\n')
  outFile.write(' * in the file named "LICENSE.txt" included with this software distribution\n')
  outFile.write(' * and also available online as http://sbml.org/software/libsbml/license.html\n')
  outFile.write(' * ------------------------------------------------------------------------ -->\n')
  outFile.write(' */\n')
    
def addCMakeFilename(outFile, filename, element):
  outFile.write('#################################################################################\n')
  outFile.write('#\n')
  outFile.write('# @file:   {0}\n'.format(filename))
  outFile.write('# @brief:  CMake configuration for L3 {0} package\n'.format(strFunctions.cap(element)))
  outFile.write('# @author: Generated by autocreate code\n#\n')

def addCMakeLicence(outFile):
  outFile.write('# <!--------------------------------------------------------------------------\n')
  outFile.write('# This file is part of libSBML.  Please visit http://sbml.org for more\n')
  outFile.write('# information about SBML, and the latest version of libSBML.\n')
  outFile.write('#\n')
  outFile.write('# Copyright (C) 2013-2014 jointly by the following organizations:\n')
  outFile.write('#     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write('#     2. EMBL European Bioinformatics Institute (EMBL-EBI), Hinxton, UK\n')
  outFile.write('#     3. University of Heidelberg, Heidelberg, Germany\n')
  outFile.write('#\n')
  outFile.write('# Copyright (C) 2009-2013 jointly by the following organizations:\n')
  outFile.write('#     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write('#     2. EMBL European Bioinformatics Institute (EMBL-EBI), Hinxton, UK\n')
  outFile.write('#\n')
  outFile.write('# Copyright (C) 2006-2008 by the California Institute of Technology,\n')
  outFile.write('#     Pasadena, CA, USA \n')
  outFile.write('#\n')  
  outFile.write('# Copyright (C) 2002-2005 jointly by the following organizations:\n') 
  outFile.write('#     1. California Institute of Technology, Pasadena, CA, USA\n')
  outFile.write('#     2. Japan Science and Technology Agency, Japan\n')
  outFile.write('#\n')
  outFile.write('# This library is free software; you can redistribute it and/or modify it\n')
  outFile.write('# under the terms of the GNU Lesser General Public License as published by\n')
  outFile.write('# the Free Software Foundation.  A copy of the license agreement is provided\n')
  outFile.write('# in the file named "LICENSE.txt" included with this software distribution\n')
  outFile.write('# and also available online as http://sbml.org/software/libsbml/license.html\n')
  outFile.write('# ------------------------------------------------------------------------ -->\n')
  outFile.write('#\n')
  